# This is Sustenance's configuration file
# There are short descriptions for each setting
# If something needs to be clarified, let me know
# .
# I have created this template for you, which I believe to be balanced
# Please change whatever you like to fit your server's needs
# .
# If you deleted a field and can't remember what to do:
# Delete or move this file and let the plugin regenerate this template
# It will only duplicate the template if the file cannot be found
# If you delete all the contents, it will not regenerate the entire file
# It will only regenerate the required headers, not entire data structures
# .
# Feel free to contact me on GitHub
# GitHub: https://github.com/danvanbueren
# .
# CAUTION: THIS IS NOT AN AI. IT CAN'T READ YOUR MIND. SPELLING MATTERS!
# REFERENCE LIST FOR FOODS: https://minecraftitemids.com/types/food
# IGNORE LEGACY ID'S, UTILIZE STANDARD ID'S
# USE ID ONLY, NOT NAMESPACE; I.E. `apple`, NOT `minecraft:apple`
# .
# -- INSTRUCTIONS
# .
# - GENERAL SETTINGS 'settings'
# 'decay-multiplier' will increase the speed at which nutrition drops
# 'verbose-logging' will send more detailed messages to the server log
# .
# - CATEGORY SETTINGS 'categories'
# Set categories and nutritional values for food items
# Categories are static (for now) - leave the datastructure as is
# .
# - EFFECT SETTINGS 'effects'
# Set effects for categories
# Set the key to category the effects will apply to
# Set the name to the effect you want to apply
# Set the threshold at the nutrition level you want effects to apply
# Set the multiplier at the intensity you want the effect to apply
# Some effects will not see any changes regardless of multiplier
# .
settings:
  decay-multiplier: 5
  verbose-logging: false
categories:
  grain:
    enchanted_golden_apple: 15
    bread: 12
    cookie: 5
    honey_bottle: 2
    chicken: -2
    spider_eye: -5
    rotten_flesh: -5
    poisonous_potato: -5
    pufferfish: -5
  protein:
    enchanted_golden_apple: 18
    cooked_beef: 15
    rabbit_stew: 15
    cooked_mutton: 14
    cooked_porkchop: 13
    cooked_chicken: 11
    cooked_rabbit: 10
    cooked_cod: 8
    cooked_salmon: 8
    beef: 5
    mutton: 5
    porkchop: 4
    suspicious_stew: 4
    honey_bottle: 4
    mushroom_stew: 3
    pumpkin_pie: 3
    rabbit: 3
    dried_kelp: 3
    cod: 2
    salmon: 2
    tropical_fish: 2
    chicken: 1
    spider_eye: -5
    pufferfish: -5
    rotten_flesh: -5
    poisonous_potato: -5
  fruit:
    enchanted_golden_apple: 15
    golden_apple: 12
    chorus_fruit: 10
    apple: 9
    honey_bottle: 7
    melon_slice: 5
    glow_berries: 5
    sweet_berries: 4
    chicken: -2
    spider_eye: -5
    rotten_flesh: -5
    poisonous_potato: -5
    pufferfish: -5
  vegetables:
    rabbit_stew: 25
    beetroot_soup: 18
    enchanted_golden_apple: 15
    suspicious_stew: 15
    pumpkin_pie: 15
    mushroom_stew: 14
    baked_potato: 12
    golden_carrot: 12
    carrot: 10
    honey_bottle: 4
    beetroot: 3
    dried_kelp: 3
    potato: 2
    chicken: -2
    spider_eye: -5
    rotten_flesh: -5
    poisonous_potato: -5
    pufferfish: -5
effects:
  major-buffs:
    haste: 2
    strength: 1
  minor-buffs:
    haste: 1
  minor-debuffs:
    hunger: 1
    slowness: 1
    mining_fatigue: 1
  major-debuffs:
    hunger: 2
    slowness: 2
    mining_fatigue: 2
    weakness: 1
    nausea: 1